.TH sfo 1 "2016-02-17" "sfo"
.SH NAME
sfo \- Simple Fuzzer Oracle (process monitoring)
.SH SYNOPSIS
\fBsfo\fR \fIPROGRAM\fR [\fIARGS\fR]...
.SH DESCRIPTION
\fBsfo\fR is a simple process monitor with some reporting capability which will
indicate that the program under test has failed, along with some basic logging
to record the failure type.
.SH USAGE
\fBsfo\fR will run an application specified on its command line with optional
arguments, and will report the application's subsequent behavior if it crashes.
.SH NOTES
\fBsfo\fR is not currently complete. It is provided as a preview.
.SH AUTHOR
.PP
Copyright \(co 2011-2016 Aaron Conole <apconole@yahoo.com>.
.PP
\fBsfo\fR and this manual are free software. They come without any
warranty, to the extent permitted by applicable law. You can redistribute
them and/or modify them under the terms of the 3-Clause BSD license. See
\fBLICENSING\fR for more details.
.PP
\fBsfo\fR is part of \fBsfuzz\fR and the site can be found at
\fBhttp://github.com/orgcandman/Simple-Fuzzer\fR
